### ISSUE TITLE
请教一些问题

### ISSUE THREAD

**Issue by lili-ux** [qq240814476/qq240814476#2]
有点事情想请教，给你发邮件了，盼回复邮件

**Comment by adamma1024** [comment]
Hello, what happened?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qq240814476/qq240814476"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月1日(星期二) 晚上6:05
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[qq240814476/qq240814476] 请教一些问题 (Issue #2)





 
有点事情想请教，给你发邮件了，盼回复邮件
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
